version: "3"

volumes:
  database:
    driver: local

services:
  database:
    image: postgres:15.1-alpine
    container_name: aop-database
    env_file:
      - .env
    ports:
      - '5431:5432'
    volumes:
      - database:/var/lib/postgresql/data

