create table if not exists books (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    author varchar(255) not null,
    publisher varchar(255) not null,
    genre varchar(128) not null,
    year_of_publication int not null,
    pages int not null
);
